name: Review workflow

on:
  pull_request:
    branches: [ dev, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          API_TESTS_VERBOSE_LOGGING: false
        run: >-
          mvn -V -e -B -ntp
          clean install sonar:sonar
          -Papi-tests-infrastructure
          -Papi-tests
          -Pjacoco -Dsonar.coverage.jacoco.xmlReportPaths=${{ github.workspace }}/home-api-tests/target/site/jacoco-aggregate/jacoco.xml
          -Dpostgres.user=${{secrets.POSTGRES_USER}}
          -Dpostgres.password=${{secrets.POSTGRES_PASSWORD}}
          -Dapi.tests.verbose.logging=${{env.API_TESTS_VERBOSE_LOGGING}}
          -Dgithub.packages.read.username=${{secrets.PACKAGES_READ_USERNAME}}
          -Dgithub.packages.read.token=${{secrets.PACKAGES_READ_TOKEN}}
